name: temperature_prediction
description: Temperature Prediction App
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.5.0+1
  file_picker: ^6.2.1
  http: ^1.5.0
  intl: ^0.20.2
  flutter_client_sse: ^2.0.3
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/background.png
    - assets/images/background2.png
